name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specifica la versione di Node.js
          registry-url: 'https://registry.npmjs.org/'  # Assicurati di utilizzare il giusto URL

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Usa il secret che hai creato
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)
          if [ "$VERSION" != "$LATEST_TAG" ]; then
            echo "Publishing version $VERSION..."
            npm publish --access public  # Assicurati di specificare l'accesso se necessario
          else
            echo "Version $VERSION is already published. Skipping publish."
          fi
