name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git fetch --tags
          
          # Attempt to get the latest tag, but handle error if no tags exist
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "none")
          
          if [ "$LATEST_TAG" = "none" ]; then
            echo "No tags found. Publishing version $VERSION..."
            npm publish --access public
          elif [ "$VERSION" != "$LATEST_TAG" ]; then
            echo "Publishing version $VERSION..."
            npm publish --access public
          else
            echo "Version $VERSION is already published. Skipping publish."
          fi
